name: CortanaCanvas
options:
  bundleIdPrefix: com.forgeandcode
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_ALLOWED: "YES"

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.24.0
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: 1.2.0

targets:
  CortanaCanvas:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "_Archive/**"
      - path: Resources/highlight.min.js
        buildPhase: resources
      - path: Resources/highlight-github-dark.min.css
        buildPhase: resources
      - path: Resources/mermaid.min.js
        buildPhase: resources
      - path: Resources/vis-network.min.js
        buildPhase: resources
    resources:
      - path: Resources/Assets.xcassets
    dependencies:
      - package: GRDB
      - package: SwiftTerm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.forgeandcode.cortana-canvas
        PRODUCT_NAME: "Cortana Canvas"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSUIElement: false
        INFOPLIST_KEY_LSMultipleInstancesProhibited: true
